<?php
/**
 * The template for displaying the footer on the site.
 * It does not use tailwind, it's SCSS file can be found at ./assets/src/sass/components/footer.scss.
 * The "Footer Columns" generated by PHP can be configured in functions.php.
 *
 * Contains the footer of the site as well as WP's required code and the closing body and HTML tags.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Bootcamp_2
 * @since 1.0.0
 */
?>

<!--Start Footer-->
<footer class="footer">

    <!--Company Logo-->
    <img src="<?php the_field('circle_outline_logo', 'options'); ?>" alt="Company Logo">
    <!--Company Info-->

    </div>

    <!--Wordpress Generated Link Lists-->
    <?php wp_nav_menu(array('theme_location' => 'footer-column-1')); ?>

    <div class="social-links">
        <a href="<?php the_field('facebook', 'options'); ?>" target="_blank"><i class="fa-brands fa-facebook"></i></a>
    </div>

    <div class="social-links">
        <a href="<?php the_field('instagram', 'options'); ?>" target="_blank"><i class="fa-brands fa-instagram"></i></a>
    </div>

    <div class="social-links">
        <a href="<?php the_field('twitter', 'options'); ?>" target="_blank"><i class="fa-brands fa-twitter"></i></a>
    </div>

    <div class="social-links">
        <a href="mailto:<?php the_field('email', 'options'); ?>"><i class="fa-light fa-envelope"></i></a>
    </div>

    <!--Copyright Info-->
    <div class="ftr-info">
        <p class = "copyright">© <?php echo date("Y"); ?> Foothills Church</p>
        <a href="/privacy-policy" class="privacy">Privacy Policy</a>
    </div>

</footer>
<!--End Footer-->


<!--Wordpress Requires This-->
<?php wp_footer(); ?>

</body>
</html>

