<?php

add_filter( 'the_seo_framework_generated_description', 'prioritized_tsf_generated_description', 10, 2 );
/**
 * Filters the generated meta description for SEO by prioritizing specific ACF layout content.
 *
 * This function modifies the meta description generated by The SEO Framework plugin
 * to use the content from ACF Flexible Content fields on the page, in a specific priority order:
 * - 'text_block'
 * - 'image_banner_text'
 * - 'information_section_block'
 * - 'blog_block'
 *
 * The function checks each layout in the specified priority order and uses the content
 * from the first available layout that contains text in the 'text_editor' subfield.
 *
 * @param string $desc The generated description from The SEO Framework plugin.
 * @param array|null $args The query arguments. Contains 'id', 'tax', 'pta', and 'uid'.
 *                         This parameter is null when the query is auto-determined.
 *
 * @return string The modified or original meta description.
 */
function prioritized_tsf_generated_description( string $desc, ?array $args ): string {

	// If ACF isn't activated, don't do anything.
	if ( ! function_exists( 'get_field' ) ) {
		return $desc;
	}

	$post_id = null;

	// Check if this is on the front-end.
	$tsfquery = tsf()->query();

	// Check if we are on a singular post or page.
	if ( $tsfquery->is_singular() ) {
		$post_id = $tsfquery->get_the_real_id();
	}

	// If post ID is available, proceed to check the 'body_sections' field.
	if ( ! empty( $post_id ) ) {
		// Get the 'body_sections' field value.
		$body_sections = get_field( 'body_sections', $post_id );

		// Priority order of layouts
		$priority_order = [
			'text_block',
			'image_banner_text',
			'information_section_block',
			'blog_block'
		];

		// Initialize an empty variable to store found content
		$editor_content = '';

		// Loop through each layout type in the priority order
		foreach ( $priority_order as $layout_type ) {
			// Reset content to avoid accidental carryover
			$editor_content = '';

			// Check each section in the body_sections for the layout type
			if ( is_array( $body_sections ) ) {
				foreach ( $body_sections as $section ) {
					if ( isset( $section['acf_fc_layout'] ) && $section['acf_fc_layout'] === $layout_type ) {
						$editor_content = $section['text_editor'] ?? '';

						// Log which layout type and content is being used for debugging.
						error_log( "Using content from: $layout_type with content: $editor_content" );

						// If valid content is found, break out of the inner loop to use this content
						if ( ! empty( $editor_content ) ) {
							break 2; // Break out of both loops since we've found the highest priority content
						}
					}
				}
			}
		}

		// If editor content is found, use it to generate the meta description.
		if ( ! empty( $editor_content ) ) {
			// Clean up and strip tags for the meta description.
			$cleaned_content = wp_strip_all_tags( $editor_content );

			// Trim the description to a maximum of 159 characters.
			if ( strlen( $cleaned_content ) > 159 ) {
				$desc = substr( $cleaned_content, 0, 156 ) . '...';
			} else {
				$desc = $cleaned_content;
			}
		}
	}

	return $desc;
}
